name: Cross Portraits
favicon: null
layout_spectrum: 0.3205704754218459
typography_spectrum: 0.6552311470732093
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.06442640977911651
  lightness: 0.3770062478724867
  saturation: 0.9188881900627166
  rhythmicContrast: 0.877502572722733
purpose: []
