name: Cross Portraits
favicon: null
layout_spectrum: 0.3205704754218459
typography_spectrum: 0.6552311470732093
title: 'Portrait & Personal Photography By David Cross (Not the Comedian)'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3b4141'
    - '#fefdfb'
    - '#b8b6b9'
    - '#5e6472'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
