name: Cross Portraits
favicon: null
layout_spectrum: 0.47895
typography_spectrum: 0.453405
title: 'Portrait & Personal Photography By David Cross (Not the Comedian)'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3b4141'
    - '#fefdfb'
    - '#b8b6b9'
    - '#5e6472'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
